version: "3"

services:
  router:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-router
    restart: unless-stopped
    network_mode: "host" # Use host network
    volumes:
      - ./config.yaml:/app/config.yaml:ro # Mount config file as read-only
    # No need to map ports when using host network
    # All ports exposed on the host will be directly used by the container
